<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [1]:
x = 10
assert x >= 0, "x is becoming negative!"
print("x is becoming positive!")

x is becoming positive!


In [2]:
x = -1
assert x >= 0, "x is becoming negative!"
print("x is becoming negative!")

AssertionError: x is becoming negative!

### 1.2 try-except

In [3]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.


ValueError: invalid literal for int() with base 10: ''

In [4]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')


Give me a number and I will calculate its square.


ValueError: invalid literal for int() with base 10: ''

In [5]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.
Oh oh! I cannot square !


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [6]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c

In [7]:
funny_add(1, 2)           # Two positional, 1 default


121

In [8]:
funny_add(1, 2, 3)        # Three positional

321

In [9]:
funny_add(a=1, b=2)       # Two keyword, 1 default

121

In [10]:
funny_add(c=3, b=1, a=2)  # Three keyword

312

In [11]:
funny_add(1, c=3, b=2)    # One positional, 2 keyword

321

In [12]:
funny_add(1, b=2)         # One positional, 1 keyword, 1 default

121

In [13]:
funny_add(a=2, 1)         # Won't work.
                          # Keywords cannot be followed by 
                          # positional

SyntaxError: positional argument follows keyword argument (25483117.py, line 1)

### 2.2 Docstrings

In [14]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [15]:
def my_function(angle, trig_function):
        return trig_function(angle)

# Let's use the function
my_function(np.pi/2, np.sin)        

1.0

In [16]:
my_function(np.pi/2, np.cos)        


6.123233995736766e-17

In [17]:
my_function(np.pi/2, lambda x: np.cos(2*x))  


-1.0

### 2.4 More unpacking

In [18]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [19]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [20]:
x, *y, g, z = np.array([1, 2, 3, 4, 5])
print(x, y, g, z)

1 [2, 3] 4 5


In [21]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [22]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def add(x, y):
    return x + y

add(x, y)

array([100, 100, 100, 100, 100])

In [23]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def subtract(x, y):
    return x - y

subtract(x, y)

array([-28, -32, -12,  52, -46])

In [24]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def multiply(x, y):
    return x * y

multiply(x, y)

array([2304, 2244, 2464, 1824, 1971])

In [31]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 0])

def divide(x, y):
    assert (y!=0).all(), "Error"
    y = np.array(y)
    return x / y

divide(x, y)

AssertionError: Error

## Exercise 2 :  A better calculator II

In [30]:
x2=np.array([36, 34, 44, 76, 27])
y2=np.array([64, 66, 56, 24, 0])

def divide(x, y):
    try:
       assert (y!=0).all()

    except:
        print("Error!")
    
    y = np.array(y)
    return x / y

divide(x2, y2)
divide(np.arange(1, 6), np.arange(5))

Error!
Error!


C:\Users\IGNATIUS\AppData\Local\Temp\ipykernel_3224\388780689.py:12: RuntimeWarning: divide by zero encountered in true_divide
  return x / y


array([       inf, 2.        , 1.5       , 1.33333333, 1.25      ])