<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [ ]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [ ]:
greeting("Super Man")

In [ ]:
greeting(name="Super Man")

In [ ]:
greet=greeting(name='Super Man')
print(greet)

In [ ]:
print(greeting(name='Super Man'))

In [ ]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [ ]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 1000])
print (list_mean)

### 1.2 Named functions that don’t return

noted

### 1.3 Anonymous functions

In [ ]:
my_short_function = lambda name: f"Hello {name}!"

In [ ]:
my_short_function(name="Super Man")

In [ ]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

In [ ]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

In [ ]:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

### 1.4 Optional arguments

In [ ]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [ ]:
greeting()

In [ ]:
?print

In [ ]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!
print('I', 'am', 'Batman!', sep='  ')

## 2 The importance of functions?

### 2.1 An argument for functions

Noted

### 2.2 A word of caution

Noted

## Exercise 1 :  Do you know why?

In [33]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
greeting("Ban")

'Hello Ban!'

Because if the if criteria is not fulfilled, the python function will move on to the next line of code, which is to return f'Hello {name}!', fulfilling the role of else?

## Exercise 2 :  Calculator functions

In [2]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def add(x, y):
    return x + y

add(x, y)

array([100, 100, 100, 100, 100])

In [4]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def subtract(x, y):
    return x - y

subtract(x, y)

array([-28, -32, -12,  52, -46])

In [5]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def multiply(x, y):
    return x * y

multiply(x, y)

array([2304, 2244, 2464, 1824, 1971])

In [4]:
x=np.array([36, 34, 44, 76, 27, 1])
y=np.array([64, 66, 56, 24, 73, 0])

def divide(x, y):
    y = np.array(y)
    if (y==0).any() :
        return "Error"
    return x / y

divide(x, y)

'Error'

In [5]:
def divide(x, y):
    y = np.array(y)
    if (y!=0).all() :
        return x / y
    return "Error"
divide(x, y)

'Error'

In [39]:
divide(9,0)

'Error'

## Exercise 3 :  max_info() with NumPy

In [32]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.max(), np.argmax(np_numbers, axis = None, out = None) + 1
max_info(numbers)

(83, 3)

In [7]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers):
    return np.max(numbers), np.argmax(numbers)
max_info(numbers)

(83, 2)