<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [4]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [4]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [6]:

print(py_real_names[0])


Natasha Romanoff


In [7]:
print(py_super_names[0])

Black Widow


In [8]:
print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.

Doctor Strange


In [9]:
print(py_super_names[-1])   # Reverse indexing

Doctor Strange


In [10]:
print(np_real_names[2])

Stephen Strange


### 1.3 Accessing data from a dictionary

In [13]:
print(list(superhero_info.values()).index("Doctor Strange"))
print(list(superhero_info.keys()))

2
['Natasha Romanoff', 'Tony Stark', 'Stephen Strange']


In [12]:
print(list(superhero_info.values()).index("Stephen Strange"))
print(list(superhero_info.keys()))

ValueError: 'Stephen Strange' is not in list

In [11]:

print(superhero_info["Natasha Romanoff"])


Black Widow


In [26]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [27]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [28]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]


In [35]:
print(py_superhero_info[1])

['Tony Stark', 'Iron Man']


## 2 Lists vs. Arrays

### 2.1 Size

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array


In [37]:
len(py_list_2d)

10

In [38]:
print(py_list_2d[9])

[10, 'J']


In [39]:
len(np_array_2d)

10

In [40]:
np_array_2d.shape

(10, 2)

In [17]:
print(np_array_2d)

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]


In [45]:
py_list_test = [[1, "A", 3], [2, "B", 3], [3, "C"]]

np_array_test = np.array(py_list_test)

np_array_test.shape


C:\Users\IGNATIUS\AppData\Local\Temp\ipykernel_50252\933081641.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np_array_test = np.array(py_list_test)


(3,)

### 2.2 Arrays are fussy about type

In [46]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [47]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array


In [50]:
py_list + py_list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [49]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [54]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)




In [56]:
py_list_1 + py_list_2


[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [55]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

In [58]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [26]:
yes = py_list*2
yes.sort()
print(yes)

[1, 1, 2, 2, 3, 3, 4, 4, 5, 5]


In [59]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [60]:

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)


In [61]:
py_list**2     

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [62]:
np_array**2


array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [64]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

In [66]:
py_list == [1, 2, 3, 4, 5]    # Works, but what IS the question?

True

In [67]:
np_array == 3  

array([False, False,  True, False, False])

In [68]:
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)      

In [69]:
sum(py_list)     # sum() is a base Python function

15

In [70]:
max(py_list)     # max() is a base Python function

5

In [71]:
min(py_list)     # min() is a base Python function

1

In [73]:
py_array = np.array(py_list)
py_array.sum()   # Won't work!

15

In [74]:
np_array.sum()

15

In [75]:
np_array.mean()


3.0

In [76]:
sum(np_array) 

15

## Exercise 1 :  Total recall?

**Similarities**
1. They are methods of data storage
2. Retrieving data follows similar code
**Differences**
1. Arrays are fussy about type, whilst lists are not, Arrays will convert all the numbers to "" if there is one letter
2. Arrays can be squared and operations work differently, for arrays, they act on each element, for lists, they act on the group together (Kind of)
**Dictionary**

A way to store and retrieve data via a key-value system.

## Exercise 2 :  Index me

In [79]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    # Prints 'a1'
                    # Prints 'c3'
                    # Prints 'e5'
                    # Prints 'g7'
print(py_list[8])   # Prints 'i9'

i9


In [87]:
print(py_list[0]) 
print(py_list[2]) 
print(py_list[4]) 
print(py_list[6]) 

a1
c3
e5
g7


## Exercise 3 :  Capitalise Heros

In [116]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info['Tony Stark'])
print(superhero_info['Natasha Romanoff'])
print(superhero_info['Stephen Strange'])
print(superhero_info)

IRON MAN
BLACK WIDOW
DOCTOR STRANGE
{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [25]:
py_list_ex4 = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]  
np_array_ex4 = np.array(py_list_ex4)

sum(np_array_ex4 == 1)

9