<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list 
print(x[0])
print(x[-1])
print(x[0:-1])
print(x[0:3])
print(x[1:6])
print(x[1:6:2])
print(x[1:6:1])
print(x[5:])
print(x[:5])
print(x[5:2:-1])
print(x[::-1])


a1
j10
['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9']
['a1', 'b2', 'c3']
['b2', 'c3', 'd4', 'e5', 'f6']
['b2', 'd4', 'f6']
['b2', 'c3', 'd4', 'e5', 'f6']
['f6', 'g7', 'h8', 'i9', 'j10']
['a1', 'b2', 'c3', 'd4', 'e5']
['f6', 'e5', 'd4']
['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']


### 1.2 Subsetting by masking (Arrays only)

In [24]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)
np_array[my_mask]

[False False False  True  True  True  True  True  True  True]


array([ 4,  5,  6,  7,  8,  9, 10])

In [25]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
justchecking = np_array > 3
print(justchecking)
np_array[justchecking]

[False False False  True  True  True  True  True  True  True]


array([ 4,  5,  6,  7,  8,  9, 10])

In [26]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [27]:
np_array[~(np_array > 3)]   

array([1, 2, 3])

In [28]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [29]:
np_array[(np_array < 3) | (np_array > 8)]     

array([ 1,  2,  9, 10])

In [30]:
np_array[(np_array > 3) | (np_array < 8)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np_array[(np_array < 3) & (np_array > 8)]     

array([], dtype=int32)

### 1.3 Indexing & Slicing 2D Lists

In [33]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
py_list_2d[3]        # What is at position 4 (index 3)?

[4, 'D']

In [34]:
py_list_2d[3][0]   

4

In [35]:
py_list_2d[3][1]   

'D'

In [36]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [37]:
py_list_2d[:3][0]

[1, 'A']

In [38]:
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [39]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [40]:
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U11')

In [41]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)


'4'

In [42]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [43]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [44]:
np_array_2d[:3, 1]

array(['A', 'B', 'C'], dtype='<U11')

In [45]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [46]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

In [47]:
print(np_array_2d[:, 0])

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


### 1.5 Growing lists

In [48]:
x=[1]*10
x               # I am lazy to type print()
                # Let Jupyter do the hard work.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [54]:
x=[1]
x= x + [2, 3]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 3, 4]

In [50]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [51]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [52]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [53]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [57]:

a=(1, 2, 3)     # Define tuple
print(a[0])
a[0]=-1
a[0] += [10]

1


TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [58]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!


In [59]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

Subsetting: Selecting a subset of elements from a list

Indexing: *Selecting element*

Slicing: *Selecting a range of elements*

Masking: Evaluating an array to see true or false and selecting the elements from there

## Exercise 2 :  Show me the ‘odd’ letters

In [43]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array = np_array_2d[:, 0]
np_array_2 = np_array.astype(int)%2  

my_mask = np_array_2 > 0
print(my_mask)
final_array = np_array_2d[my_mask]
final_array[:, 1]


[ True  True False False  True  True False False False  True]


array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')